apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: assignment2-db
  labels:
    app: mysqldb
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysqldb