apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-depolyment
  namespace: assignment2-db
  labels:
    app: mysqldb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-db
        image: 955996620086.dkr.ecr.us-east-1.amazonaws.com/assignment2-myrepo:mysql-image-v1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "cg1225_clo835"
        ports:
        - containerPort: 3306
          protocol: TCP