name: push images to ECR

on:
  push:
    branches: [ main,dev ]

jobs:
  build:
    name: Build and Push Images to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build the web app image and push to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: assignment2-myrepo
        IMAGE_TAG: v1.0
      run: |
        # Docker build
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:webapp-image-$IMAGE_TAG -f Dockerfile .
        docker ps
        #ECR push
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:webapp-image-$IMAGE_TAG

    - name: Build MySQL image and push to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: assignment2-myrepo
        IMAGE_TAG: v1.0
      run: |
        # Docker build
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:mysql-image-$IMAGE_TAG -f Dockerfile_mysql .
        docker ps
        # ECR push
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:mysql-image-$IMAGE_TAG
